title       = "theodinproject"
baseURL     = "https://theodinproject-cli.tamnd.com/"
description = "A command line for theodinproject."
contentDir  = "content"
outputDir   = "public"
theme       = "tago-doks"
syntaxHighlight = "true"

[params]
github = "https://github.com/tamnd/theodinproject-cli"
